### ISSUE TITLE
Капча

### ISSUE THREAD

**Issue by Opiumtm** [TrixiEther/Dashchan-Extensions#16]
Там мохнатый пидарас Абу врубил вместо цифровой 2ch капчи цифры с буквами. А в клиенте поле ввода двач-капчи цифровое, и в итоге постинг - опять всё, спасибо скажем пидору обезьяне.

**Comment by TrixiEther** [comment]
@Opiumtm https://github.com/TrixiEther/Dashchan-Extensions/releases/tag/hotfix6.1
Выставил тип с цифрами и латинскими буквами, встанет поверх fix6

**Comment by TrixiEther** [comment]
@Opiumtm я уже подумываю, но ту не получится уже без изменения самого клиента. Все настройки подразумеваются общими для всех чанов в принципе, а такого, чтобы какая-то изменяемая пользователем конфигурация для отдельного расширения - не завезли

**Comment by Opiumtm** [comment]
@Opiumtm Так есть же отдельная страница настройки для двача! Там, где базовый адрес вводится и тип капчи
