### ISSUE TITLE
[Bug] Desuarchive doesn't work...properly

### ISSUE THREAD

**Issue by darlopvil** [TrixiEther/Dashchan-Extensions#32]
A thread "doesn't charge very well" when opening an archived thread with desuarchive.org

Nowadays i've to use another app to consult the archive because of this. See this 2 captures as example:

![imagen](https://user-images.githubusercontent.com/60988792/235263230-16ecc520-e14d-458f-8bb4-e6ba0c85ac24.png)

this is the correct version

![imagen](https://user-images.githubusercontent.com/60988792/235263271-8f7f8710-9203-4f93-9510-87ca008d21cb.png)

and this is the dashchan weird version

**Comment by TrixiEther** [comment]
@darlopvil hi, could you share a link to a specific problematic thread?

**Comment by darlopvil** [comment]
sure: https://desuarchive.org/int/thread/176086034

**Comment by TrixiEther** [comment]
Looks like a page parsing issue. I got the response in the module and the html page is identical to what I get in the browser. All posts are in place.

**Comment by darlopvil** [comment]
> I got the response in the module and the html page is identical to what I get in the browser. 
> All posts are in place.

?
so it works for you but not for me?

**Comment by TrixiEther** [comment]
@darlopvil doesn't work for me either, will need to check the code. It seems that all the posts that contained katakana were lost...

**Comment by darlopvil** [comment]
Oh, i misunderstood. Thanks 🙏

**Comment by TrixiEther** [comment]
Closed as duplicate #50
