### ISSUE TITLE
Signed apk

### ISSUE THREAD

**Issue by tsunamaru** [TrixiEther/Dashchan-Extensions#5]
Привет,  

Во-первых, спасибо за фиксы. Реально огромное спасибо.  
Во-вторых, я заметил что в релизах лежит неподписанный апк. Такой апк не поставится на стоковый андроид с включенной проверкой подписей, его надо подписать каким-нибудь ключом.  

Так уж получилось, что апк который сейчас лежит в треде моби собрал я, сгенерив для него ключ, и его все растащили, поэтому предлагаю передать тебе ключ, если ты собираешься делать какие-то правки дальше. Это избавит людей от необходимости потом удалять расширение и ставить его заново из-за разницы в подписях.  
Ну а если не собираешься -- то может просто добавишь подписанный апк в ассеты?  

Если что, мои контакты есть в профиле гитхаба.

**Comment by TrixiEther** [comment]
Разве так не обязателен Google Play для этого, или главное только чтобы он был подписанным?

Раз такое дело, то сделаем, чуть позднее отпишу, пусть уже будет с одним ключом

**Comment by tsunamaru** [comment]
Google Play не обязателен, ключ можно сгенерить прямо в студии. Ведру без разницы каким ключем была сделана подпись, главное чтобы она была.

**Comment by TrixiEther** [comment]
@tsunamaru пришлось таки сгенерить свой ключ, буду теперь подписывать им

**Comment by tsunamaru** [comment]
@TrixiEther давай может все таки доразберёмся в чем проблема? В крайнем случае я ci на github-actions могу сделать чтобы само собиралось.

**Comment by tsunamaru** [comment]
Вижу что у тебя получилось сделать CI с ключиком. Протестил артифакт из https://github.com/TrixiEther/Dashchan-Extensions/actions/runs/2918636680 - все супер, устанавливается без проблем.

**Comment by tsunamaru** [comment]
Closed in https://github.com/TrixiEther/Dashchan-Extensions/releases/tag/fix5
