### ISSUE TITLE
[Bug] archived.moe doesn't show japanese-written posts.

### ISSUE THREAD

**Issue by darlopvil** [TrixiEther/Dashchan-Extensions#50]
What's up.

It's the same problem as in #32 

GOOD VERSION (although images don't appear, idk why):

[![1.jpg](https://i.postimg.cc/XNRDv0bM/1.jpg)](https://postimg.cc/V5FF7pv4)

BUGGED VERSION (only posts in english):

[![2.jpg](https://i.postimg.cc/Bn9WRK6K/2.jpg)](https://postimg.cc/nCkwDMqF)

Direct link to the thread hosted in archived.moe: https://archived.moe/int/thread/178630770

---------------
i'm sorry for creating a new bug issue shortly after you created the apk. I know it can be tiresome at some point.

Thank you 🙏

**Comment by TrixiEther** [comment]
yes, it looks like the problem is only with the FoolFuuka engine...
in this case, I suspend the development of modules that use this engine, otherwise it will have to be rebuilt later

**Comment by darlopvil** [comment]
Sad to read that. I'll be waiting for more updates though.
Thanks, don't push yourself too much 🤝

**Comment by TrixiEther** [comment]
@darlopvil try this:

https://github.com/TrixiEther/Dashchan-Meta/raw/master/update/package/DashchanArchivedMoe.apk
https://github.com/TrixiEther/Dashchan-Meta/raw/master/update/package/DashchanDesustorage.apk

**Comment by darlopvil** [comment]
Now it works! Japanese posts appear to be working correctly. Thank you so much!

**Comment by TrixiEther** [comment]
Closed
